-- sdd/patient-self-scheduling PR 1 (design.md "Interfaces / Contracts" +
-- "File Changes"): schema foundation for the patient self-scheduling
-- portal -- recurring weekly schedule (TherapistAvailability), blockout
-- exceptions (AvailabilityBlockout), Chile public holidays
-- (PublicHoliday), and the double-booking race guard for the public
-- booking write path (BookedSlot). No backfill: additive only, no existing
-- table is touched besides the new nullable User.sessionDurationMinutes
-- column (design.md "Migration / Rollout").

-- CreateEnum
CREATE TYPE "BlockoutKind" AS ENUM ('FULL_DAY', 'PARTIAL_DAY', 'DATE_RANGE');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "sessionDurationMinutes" INTEGER;

-- CreateTable
CREATE TABLE "TherapistAvailability" (
    "id" TEXT NOT NULL,
    "therapistId" TEXT NOT NULL,
    "dayOfWeek" INTEGER NOT NULL,
    "startMinute" INTEGER NOT NULL,
    "endMinute" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TherapistAvailability_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AvailabilityBlockout" (
    "id" TEXT NOT NULL,
    "therapistId" TEXT NOT NULL,
    "startsAt" TIMESTAMP(3) NOT NULL,
    "endsAt" TIMESTAMP(3) NOT NULL,
    "kind" "BlockoutKind" NOT NULL,
    "reason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AvailabilityBlockout_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PublicHoliday" (
    "id" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "name" TEXT NOT NULL,
    "countryCode" TEXT NOT NULL DEFAULT 'CL',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PublicHoliday_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BookedSlot" (
    "id" TEXT NOT NULL,
    "therapistId" TEXT NOT NULL,
    "groupId" TEXT NOT NULL,
    "slotStart" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "BookedSlot_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TherapistAvailability_therapistId_idx" ON "TherapistAvailability"("therapistId");

-- CreateIndex
CREATE UNIQUE INDEX "TherapistAvailability_therapistId_dayOfWeek_startMinute_key" ON "TherapistAvailability"("therapistId", "dayOfWeek", "startMinute");

-- CreateIndex
CREATE INDEX "AvailabilityBlockout_therapistId_startsAt_idx" ON "AvailabilityBlockout"("therapistId", "startsAt");

-- CreateIndex
CREATE UNIQUE INDEX "PublicHoliday_date_countryCode_key" ON "PublicHoliday"("date", "countryCode");

-- CreateIndex
CREATE UNIQUE INDEX "BookedSlot_groupId_key" ON "BookedSlot"("groupId");

-- CreateIndex
CREATE UNIQUE INDEX "BookedSlot_therapistId_slotStart_key" ON "BookedSlot"("therapistId", "slotStart");

-- AddForeignKey
ALTER TABLE "TherapistAvailability" ADD CONSTRAINT "TherapistAvailability_therapistId_fkey" FOREIGN KEY ("therapistId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AvailabilityBlockout" ADD CONSTRAINT "AvailabilityBlockout_therapistId_fkey" FOREIGN KEY ("therapistId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BookedSlot" ADD CONSTRAINT "BookedSlot_therapistId_fkey" FOREIGN KEY ("therapistId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Supabase "rls_disabled_in_public" (same convention as migrations
-- 20260804170000, 20260825170000, 20260825180000, 20260826120000,
-- 20260828190000, and 20260909190000): every new table in the public
-- schema must enable RLS deny-all (no policies) to close exposure via
-- Supabase's autogenerated PostgREST API. The runtime role
-- (DATABASE_URL/DIRECT_URL) has rolbypassrls=true, so this changes
-- nothing for the app itself.
ALTER TABLE "TherapistAvailability" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AvailabilityBlockout" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PublicHoliday" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BookedSlot" ENABLE ROW LEVEL SECURITY;
